import type { Metadata } from 'next';
import { Aldrich } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { cn } from '@/lib/utils';

const aldrichSans = Aldrich({
  weight: '400',
  display: 'swap',
  variable: '--font-aldrich',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          aldrichSans.variable
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
